namespace MMZ.DTOs;

public class AlbumDTO
{
    // Id is auto-generated by database, so we don't need it in DTO
    public int UserId { get; set; }
    public int? ArtistId { get; set; }
    public string? EanUpc { get; set; }
    public string? CodeRequest { get; set; }
    public string Title { get; set; } = null!;
    public string? Subtitle { get; set; }
    public DateTime? OriginalReleaseDate { get; set; }
    public DateTime? DigitalReleaseDate { get; set; }
    public string? Redistribution { get; set; }
    public string? SpotifyArtistUrl { get; set; }
    public string? AppleArtistUrl { get; set; }
    public string? CoverPath { get; set; } // Base64 string from frontend
    public string? Status { get; set; }
    public int? StyleId { get; set; }
    // CreatedAt and UpdatedAt will be set automatically on the server
}
