namespace MMZ.DTOs;

public class TrackDTO
{
    // Id is auto-generated by database
    public int AlbumId { get; set; }
    public int TrackNumber { get; set; }
    public string Title { get; set; } = null!;
    public string? Subtitle { get; set; }
    public string? IsrcRequest { get; set; }
    public DateTime? OriginalReleaseDate { get; set; }
    public string? Collaborators { get; set; }
    public string? ExplicitLyrics { get; set; }
    public string? Composers { get; set; }
    public string? Lyricists { get; set; }
    public string? AudioPath { get; set; } // Base64 string from frontend
    public int? StyleId { get; set; }
}
